image: docker:19.03.13

variables:
  IMAGE_NAME: "impfsolidaritaet-frontend"
  DEPLOYMENT_NAME: "deployment/impfsolidaritaet-frontend"
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_TLS_VERIFY: 1
  DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"

services:
  - docker:19.03.13-dind

stages:
  - build-prod
  - deploy-prod

build-prod:
  stage: build-prod
  script:
    - |
      for i in $(seq 1 30)
      do
          docker info && break
          echo "Waiting for docker to start"
          sleep 1s
      done
    - docker login $DOCKER_REGISTRY -u nologin -p $SCW_SECRET_TOKEN
    - docker build -t $DOCKER_REGISTRY/prod/$IMAGE_NAME:$CI_COMMIT_SHORT_SHA -t $DOCKER_REGISTRY/prod/$IMAGE_NAME:latest -f Dockerfile.prod .
    - docker push $DOCKER_REGISTRY/prod/$IMAGE_NAME:$CI_COMMIT_SHORT_SHA
    - docker push $DOCKER_REGISTRY/prod/$IMAGE_NAME:latest

deploy-prod:
  image:
    name: bitnami/kubectl
    entrypoint: [""]
  stage: deploy-prod
  tags:
    - docker
  environment: kubernetes
  dependencies:
    - build-prod
  script:
    - kubectl set image $DEPLOYMENT_NAME web=$DOCKER_REGISTRY/prod/$IMAGE_NAME:$CI_COMMIT_SHORT_SHA --record -n vaccine
