version: '3'
services:
  az-info:
    container_name: az-info
    build:
      context: .
      dockerfile: Dockerfile.local
    volumes:
      - ./app/src:/app/src
      - /app/node_modules
    ports:
      - "8081:3000"
    environment:
      REACT_APP_STAGE: "local"
